services:
  frontend:
    container_name: frontend
    image: DockerProjekti/frontend
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    container_name: backend
    image: DockerProjekti/backend
    build: ./backend
    volumes:
      - message_data:/app/data/
    ports:
      - 5000:5000
volumes:
  message_data:
